/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://aq4krhwndnaxtk7viz2kpxtwam.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-eb4j62k7djht7k63ht4ctstik4",
    "userPoolId": "us-east-2_qaY3p7wdo",
    "userPoolWebClientId": "34oc7jjcjjd3g4fq7vq1errjp"
};


export default awsmobile;
